name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # replace with your default branch if not master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t .

    - name: Package Lambda function
      run: |
        zip -r lambda_function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # replace with your AWS region

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name auto_trade --zip-file fileb://lambda_function.zip
